# This person is my savior http://panavtec.me/continous-integration-on-android-with-travis-ci

sudo: false

language: android

jdk:
  - oraclejdk8

env:
  matrix:
    - ANDROID_TARGET=android-23 ANDROID_ABI=armeabi-v7a

android:
  components:
  - platform-tools
  - tools
  - build-tools-23.0.3
  - android-23
  - extra-android-m2repository
  - extra-google-m2repository
  - sys-img-armeabi-v7a-$ANDROID_TARGET

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock


before_script:
  - android list targets
  - echo no | android create avd --force -n test -t $ANDROID_TARGET
  - emulator -avd test -no-audio -no-window -no-skin &

script:
  - ./gradlew check -PdisablePreDex --continue --stacktrace
  - android-wait-for-emulator
  - adb shell settings put global window_animation_scale 0 &
  - adb shell settings put global transition_animation_scale 0 &
  - adb shell settings put global animator_duration_scale 0 &
  - adb shell input keyevent 82 &
  - ./gradlew connectedAndroidTest -PdisablePreDex --continue --stacktrace

after_failure:
  - wget http://imgur.com/tools/imgurbash.sh
  - chmod a+x imgurbash.sh
  - adb shell screencap -p | sed 's/\r$//' &gt; screen.png
  - ./imgurbash.sh screen.png
  - pandoc builder/build/reports/tests/index.html -t plain | sed -n '/^Failed tests/,/default-package/p'


cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
